/*
 * ContenedorDatos.java
 *
 * ADICO: Desarrollo de dos versiones de una Aplicación para el DIseño de COcinas,
 * una con interfaz de usuario tipo WIMP y otra con interfaz IGO.
 *
 * Realizado por: Manuel Flores Vivas <mflores at alu.uma.es>
 * Tutor: Antonio Luis Carrillo León <alcarrillo at uma.es>
 *
 * Proyecto Fin de Carrera
 * Ingeniería Técnica en Informática de Sistemas (Universidad de Málaga)
 */

package igo;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author Manuel Flores Vivas
 */
public class ContenedorDatos extends javax.swing.JPanel implements vista.InterfazBarraEstado {
    
    private int foco = 0;
    private Timer t;

    /** Creates new form ContenedorDatos */
    public ContenedorDatos() {
        initComponents();
        jLabelEstado.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelA = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabelA.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelA.setText("Introduzca su nombre completo:");

        jTextFieldA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAActionPerformed(evt);
            }
        });
        jTextFieldA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAFocusLost(evt);
            }
        });
        jTextFieldA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 25));

        jLabelEstado.setBackground(new java.awt.Color(255, 99, 93));
        jLabelEstado.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabelEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(136, 6, 6), 2));
        jLabelEstado.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelA, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(228, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jLabelA)
                .addGap(32, 32, 32)
                .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jTextFieldAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAActionPerformed
    controlador.Controlador.getInstance().getVco2().simularClick();
}//GEN-LAST:event_jTextFieldAActionPerformed

private void jTextFieldAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAFocusLost
    if (foco==0) {
        jTextFieldA.requestFocus();
        foco++;
    } else {
        if (jTextFieldA.isEditable() && (evt.getOppositeComponent()!=null) && (evt.getOppositeComponent().getClass() == JTextField.class )) {
            jTextFieldA.requestFocus();
        }
    }
}//GEN-LAST:event_jTextFieldAFocusLost

private void jTextFieldAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAKeyPressed
    controlador.Controlador.getInstance().cambiarEstado("Listo");
}//GEN-LAST:event_jTextFieldAKeyPressed

    public String getNombre() {
        return jTextFieldA.getText();
    }

    public void activa(char c) {
        jTextFieldA.setEditable(false);
        jTextFieldA.setSelectionEnd(0); //y deseleccionamos los campos de texto
        
        switch(c) {
            case 'a': jTextFieldA.setEditable(true);
                    jTextFieldA.requestFocus();
                    jTextFieldA.setSelectionStart(0);
                    jTextFieldA.setSelectionEnd(jTextFieldA.getText().length());
                    break;
        }
    }

    //cambia u oculta el mensaje en la barra superior de estado
    public void cambiarEstado(String estado) {
        if (t!=null) { //timer
                t.stop();
        }

        if (estado.equals("Listo") || estado.equals("")) {
            jLabelEstado.setVisible(false);
        } else {
            jLabelEstado.setVisible(true);
            jLabelEstado.setText(" ".concat(estado));

            //timer blink
            t = new Timer(400, new ActionListener() {
                Color rosa = new Color(255,99,93);
                Color marron = new Color(220,46,46);
                boolean estado = false;
                public void actionPerformed(ActionEvent e) {
                    jLabelEstado.setBackground(estado?marron:rosa);
                    estado=!estado;
                }
            });
            t.setInitialDelay(200);
            t.start();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldA;
    // End of variables declaration//GEN-END:variables

}
