/*
 * ContenedorMedidas.java
 *
 * ADICO: Desarrollo de dos versiones de una Aplicación para el DIseño de COcinas,
 * una con interfaz de usuario tipo WIMP y otra con interfaz IGO.
 *
 * Realizado por: Manuel Flores Vivas <mflores at alu.uma.es>
 * Tutor: Antonio Luis Carrillo León <alcarrillo at uma.es>
 *
 * Proyecto Fin de Carrera
 * Ingeniería Técnica en Informática de Sistemas (Universidad de Málaga)
 */

package igo;

import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  Manuel Flores Vivas
 */
public class ContenedorMedidas extends javax.swing.JPanel implements vista.InterfazBarraEstado {
    
    private int forma;
    private int foco = 0;
    private Timer t;
    
    /** Creates new form ContenedorMedidas */
    public ContenedorMedidas() {
        initComponents();
        jLabelEstado.setVisible(false);
    }
    
    public void setForma(int num) { //muestra la miniatura y habilita los campos necesarios
        forma = num;
        previsualizacion.setIcon(new javax.swing.ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m.gif"));
        
        jLabelC.setVisible(forma>2);
        jLabelD.setVisible(forma>2);
        jTextFieldC.setVisible(forma>2);
        jTextFieldD.setVisible(forma>2);
        jLabel3.setVisible(forma>2);
        jLabel4.setVisible(forma>2);
        jLabel7.setVisible(forma>2);
        jLabel8.setVisible(forma>2);
    }
    
    //metodos para conseguir los valores introducidos
    public int getA() {
        return Integer.parseInt(jTextFieldA.getText());
    }
    
    public int getB() {
        return Integer.parseInt(jTextFieldB.getText());
    }
    
    public int getC() {
        return Integer.parseInt(jTextFieldC.getText());
    }
    
    public int getD() {
        return Integer.parseInt(jTextFieldD.getText());
    }

    public JTextField getJTextFieldA() {
        return jTextFieldA;
    }

    public JTextField getJTextFieldB() {
        return jTextFieldB;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previsualizacion = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jTextFieldA = new javax.swing.JTextField();
        jTextFieldB = new javax.swing.JTextField();
        jTextFieldC = new javax.swing.JTextField();
        jTextFieldD = new javax.swing.JTextField();
        jLabelC = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        previsualizacion.setPreferredSize(new java.awt.Dimension(277, 209));

        jLabelA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelA.setText("Lado A");

        jLabelB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelB.setText("Lado B");

        jTextFieldA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAActionPerformed(evt);
            }
        });
        jTextFieldA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAFocusLost(evt);
            }
        });
        jTextFieldA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAKeyPressed(evt);
            }
        });

        jTextFieldB.setEditable(false);
        jTextFieldB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBActionPerformed(evt);
            }
        });
        jTextFieldB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBFocusLost(evt);
            }
        });
        jTextFieldB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBKeyPressed(evt);
            }
        });

        jTextFieldC.setEditable(false);
        jTextFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCActionPerformed(evt);
            }
        });
        jTextFieldC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCFocusLost(evt);
            }
        });
        jTextFieldC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCKeyPressed(evt);
            }
        });

        jTextFieldD.setEditable(false);
        jTextFieldD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDActionPerformed(evt);
            }
        });
        jTextFieldD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDFocusLost(evt);
            }
        });
        jTextFieldD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDKeyPressed(evt);
            }
        });

        jLabelC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelC.setText("Lado C");

        jLabelD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelD.setText("Lado D");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("cent�metros");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("cm.");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("cm.");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("cm.");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(358, 25));

        jLabelEstado.setBackground(new java.awt.Color(255, 99, 93));
        jLabelEstado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEstado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(136, 6, 6), 2));
        jLabelEstado.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Ejemplo:  300");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ejemplo: 400");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ejemplo: 200");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ejemplo: 150");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelA)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelB)
                                        .addGap(1, 1, 1)))
                                .addGap(1, 1, 1))
                            .addComponent(jLabelC)
                            .addComponent(jLabelD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldA, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jTextFieldB)
                            .addComponent(jTextFieldC)
                            .addComponent(jTextFieldD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(previsualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previsualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelB)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC)
                            .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelD)
                    .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAActionPerformed
        if (jTextFieldA.isEditable()) controlador.Controlador.getInstance().getVco2().simularClick();
    }//GEN-LAST:event_jTextFieldAActionPerformed

    private void jTextFieldBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBActionPerformed
        if (jTextFieldB.isEditable()) controlador.Controlador.getInstance().getVco2().simularClick();
    }//GEN-LAST:event_jTextFieldBActionPerformed

    private void jTextFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCActionPerformed
        if (jTextFieldC.isEditable()) controlador.Controlador.getInstance().getVco2().simularClick();
    }//GEN-LAST:event_jTextFieldCActionPerformed

    private void jTextFieldDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDActionPerformed
        if (jTextFieldD.isEditable()) controlador.Controlador.getInstance().getVco2().simularClick();
    }//GEN-LAST:event_jTextFieldDActionPerformed

    private void jTextFieldAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAFocusLost
        if (foco==0) {
            jTextFieldA.requestFocus();
            foco++;
        } else {
            if (jTextFieldA.isEditable() && (evt.getOppositeComponent()!=null) && (evt.getOppositeComponent().getClass() == javax.swing.JTextField.class )) {
                jTextFieldA.requestFocus();
            }
        }
    }//GEN-LAST:event_jTextFieldAFocusLost

    private void jTextFieldAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAKeyPressed
        controlador.Controlador.getInstance().cambiarEstado("Listo");
    }//GEN-LAST:event_jTextFieldAKeyPressed

    private void jTextFieldBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBKeyPressed
        controlador.Controlador.getInstance().cambiarEstado("Listo");
    }//GEN-LAST:event_jTextFieldBKeyPressed

    private void jTextFieldCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCKeyPressed
        controlador.Controlador.getInstance().cambiarEstado("Listo");
    }//GEN-LAST:event_jTextFieldCKeyPressed

    private void jTextFieldDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDKeyPressed
        controlador.Controlador.getInstance().cambiarEstado("Listo");
    }//GEN-LAST:event_jTextFieldDKeyPressed

    private void jTextFieldBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBFocusLost
        if (jTextFieldB.isEditable() && (evt.getOppositeComponent()!=null) && (evt.getOppositeComponent().getClass() == javax.swing.JTextField.class )) {
                jTextFieldB.requestFocus();
            }
    }//GEN-LAST:event_jTextFieldBFocusLost

    private void jTextFieldCFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCFocusLost
        if (jTextFieldC.isEditable() && (evt.getOppositeComponent()!=null) && (evt.getOppositeComponent().getClass() == javax.swing.JTextField.class )) {
                jTextFieldC.requestFocus();
            }
    }//GEN-LAST:event_jTextFieldCFocusLost

    private void jTextFieldDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDFocusLost
        if (jTextFieldD.isEditable() && (evt.getOppositeComponent()!=null) && (evt.getOppositeComponent().getClass() == javax.swing.JTextField.class )) {
                jTextFieldD.requestFocus();
            }
    }//GEN-LAST:event_jTextFieldDFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldD;
    private javax.swing.JLabel previsualizacion;
    // End of variables declaration//GEN-END:variables
    
    public void activa(char c) {
        jTextFieldA.setEditable(false);
        jTextFieldB.setEditable(false);
        jTextFieldC.setEditable(false);
        jTextFieldD.setEditable(false);
        jTextFieldA.setSelectionEnd(0); //y deseleccionamos los campos de texto
        jTextFieldB.setSelectionEnd(0);
        jTextFieldC.setSelectionEnd(0);
        jTextFieldD.setSelectionEnd(0);
// ALUIS: PARA IR MOSTRANDO CUADRO INTRODUCCI�N DE CADA MEDIDA SEGUN TOQUE

jTextFieldA.setVisible(true);    

jTextFieldB.setVisible(true);  
   jLabelB.setVisible(true);
   jLabel2.setVisible(true);
   
jTextFieldC.setVisible(true);  
   jLabelC.setVisible(true);
   jLabel3.setVisible(true);
   
jTextFieldD.setVisible(true);        
   jLabelD.setVisible(true);
   jLabel4.setVisible(true); 
        
        switch(c) {
            case 'a': jTextFieldA.setEditable(true);


                    jTextFieldA.requestFocus();
                    jTextFieldA.setSelectionStart(0);
                    jTextFieldA.setSelectionEnd(jTextFieldA.getText().length());

//jTextFieldA.setText("000");                          
jTextFieldA.setVisible(true);

if (jTextFieldB.getText().equals("") ){
   jTextFieldB.setVisible(false); 
   jLabelB.setVisible(false);
   jLabel2.setVisible(false);
}
else {
   jTextFieldB.setVisible(true); 
   jLabelB.setVisible(true);
   jLabel2.setVisible(true);

}

if (jTextFieldC.getText().equals("") ){
   jTextFieldC.setVisible(false); 
   jLabelC.setVisible(false);
   jLabel3.setVisible(false);
}
else {
   jTextFieldC.setVisible(true); 
   jLabelC.setVisible(true);
   jLabel3.setVisible(true);

}

if (jTextFieldD.getText().equals("") ){
   jTextFieldD.setVisible(false); 
   jLabelD.setVisible(false);
   jLabel4.setVisible(false);
}
else {
   jTextFieldD.setVisible(true); 
   jLabelD.setVisible(true);
   jLabel4.setVisible(true);

}
  
 
                    previsualizacion.setIcon(new ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m_a.gif"));
                    break;
            case 'b': jTextFieldB.setEditable(true);

//jTextFieldA.setVisible(true);        
//jTextFieldB.setVisible(true);           

if (jTextFieldC.getText().equals("") ){
   jTextFieldC.setVisible(false); 
   jLabelC.setVisible(false);
   jLabel3.setVisible(false);
}
else {
   jTextFieldC.setVisible(true); 
   jLabelC.setVisible(true);
   jLabel3.setVisible(true);

}

if (jTextFieldD.getText().equals("") ){
   jTextFieldD.setVisible(false); 
   jLabelD.setVisible(false);
   jLabel4.setVisible(false);
}
else {
   jTextFieldD.setVisible(true); 
   jLabelD.setVisible(true);
   jLabel4.setVisible(true);

}

                    jTextFieldB.requestFocus();
                    jTextFieldB.setSelectionStart(0);
                    jTextFieldB.setSelectionEnd(jTextFieldB.getText().length());
                    previsualizacion.setIcon(new ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m_b.gif"));
                    break;
            case 'c': jTextFieldC.setEditable(true);
            
//jTextFieldA.setVisible(true);        
//jTextFieldB.setVisible(true);        
//jTextFieldC.setVisible(true);        

if (jTextFieldD.getText().equals("") ){
   jTextFieldD.setVisible(false); 
   jLabelD.setVisible(false);
   jLabel4.setVisible(false);
}
else {
   jTextFieldD.setVisible(true); 
   jLabelD.setVisible(true);
   jLabel4.setVisible(true);

}

                    jTextFieldC.requestFocus();
                    jTextFieldC.setSelectionStart(0);
                    jTextFieldC.setSelectionEnd(jTextFieldC.getText().length());
                    previsualizacion.setIcon(new ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m_c.gif"));
                    break;
            case 'd': jTextFieldD.setEditable(true);
            
jTextFieldA.setVisible(true);        
jTextFieldB.setVisible(true);        
jTextFieldC.setVisible(true);        
jTextFieldD.setVisible(true);   

                    jTextFieldD.requestFocus();
                    jTextFieldD.setSelectionStart(0);
                    jTextFieldD.setSelectionEnd(jTextFieldD.getText().length());
                    previsualizacion.setIcon(new ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m_d.gif"));
                    break;
            default:
                    previsualizacion.setIcon(new ImageIcon("imagenes" + File.separator + "formas" + File.separator + "forma"+Integer.toString(forma)+"m.gif"));
                    break;
        }
    }
    
    public void foco(char c) {
        activa(c);
    }

    //cambia u oculta el mensaje en la barra superior de estado
    public void cambiarEstado(String estado) {
        if (t!=null) { //timer
                t.stop();
        }

        if (estado.equals("Listo") || estado.equals("")) {
            jLabelEstado.setVisible(false);
        } else {
            jLabelEstado.setVisible(true);
            jLabelEstado.setText(" ".concat(estado));

            //timer blink
            t = new Timer(400, new ActionListener() {
                Color rosa = new Color(255,99,93);
                Color marron = new Color(220,46,46);
                boolean estado = false;
                public void actionPerformed(ActionEvent e) {
                    jLabelEstado.setBackground(estado?marron:rosa);
                    estado=!estado;
                }
            });
            t.setInitialDelay(200);
            t.start();
        }
    }

}
