/*
 * ElementoCatalogo.java
 *
 * ADICO: Desarrollo de dos versiones de una Aplicaci√≥n para el DIse√±o de COcinas,
 * una con interfaz de usuario tipo WIMP y otra con interfaz IGO.
 *
 * Realizado por: Manuel Flores Vivas <mflores at alu.uma.es>
 * Tutor: Antonio Luis Carrillo Le√≥n <alcarrillo at uma.es>
 *
 * Proyecto Fin de Carrera
 * Ingenier√≠a T√©cnica en Inform√°tica de Sistemas (Universidad de M√°laga)
 */

package galeria;

import javax.swing.*;
import java.text.*;

/**
 *
 * @author  Manuel Flores Vivas
 */
public class ElementoCatalogo extends javax.swing.JPanel {
    private String fichero;

    /** Creates new form ElementoCatalogo */
    public ElementoCatalogo() {
        initComponents();
    }
    
    public void rellenarElemento(String fichero, String imagen, String nombre, String tipo, String descripcion, int altura, int anchura, int profundidad, float precio) {
        this.fichero = fichero;
        this.imagen.setIcon(new ImageIcon(imagen));
        this.nombre.setText(nombre);
        this.tipo.setText(tipo);

        DecimalFormat df = new DecimalFormat("0.##");
        if (descripcion!=null) {
            this.descripcion.setText(descripcion);
            if (altura!=0) {
                if (profundidad!=0) {
                    //flechas unicode: ‚Üï ?‚ Üî ?‚ ûö ?
                    this.dimensiones.setText(Integer.toString(altura)+" x "+Integer.toString(anchura) + " x "+Integer.toString(profundidad) +" cm");
                } else {
                    this.dimensiones.setText(Integer.toString(altura)+" x "+Integer.toString(anchura) +" cm");
                }
                if (precio!=0) {
                    this.precio.setText(df.format(precio) + " €");
                } else {
                    this.precio.setText(" ");
                }
            } else {
                //reajuste
                if (precio!=0) {
                    this.dimensiones.setText(df.format(precio)  + " €");
                } else {
                    this.dimensiones.setText(" ");
                }
                this.precio.setText(" ");
            }
        } else {
            if (altura!=0) {
                if (profundidad!=0) {
                    this.descripcion.setText(Integer.toString(altura)+" x "+Integer.toString(anchura) + " x "+Integer.toString(profundidad) +" cm");
                } else {
                    this.descripcion.setText(Integer.toString(altura)+" x "+Integer.toString(anchura) +" cm");
                }
                if (precio!=0) {
                    this.dimensiones.setText(df.format(precio) + " €");
                } else {
                    this.dimensiones.setText(" ");
                    this.precio.setText(" ");
                }
            } else {
                //reajuste
                if (precio!=0) {
                    this.descripcion.setText(df.format(precio)  + " €");
                } else {
                    this.descripcion.setText(" ");
                }
                this.dimensiones.setText(" ");
                this.precio.setText(" ");
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        dimensiones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(161, 205));
        setMinimumSize(new java.awt.Dimension(161, 205));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");

        tipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipo.setText("Tipo");
        tipo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        precio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        precio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio.setText("Precio");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        descripcion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcion.setText("Descripcion");

        dimensiones.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        dimensiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimensiones.setText("Dimensiones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(dimensiones, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(tipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dimensiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precio))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //notificar
        if (this.isEnabled()) {
            controlador.Controlador.getInstance().elementoCatClick(fichero);
            //seleccionar
            ((Catalogo)this.getParent().getParent().getParent()).deseleccionarTodo();
            this.setBorder(new javax.swing.border.EtchedBorder());
            controlador.Controlador.getInstance().cambiarEstado("Listo");
        }
    }//GEN-LAST:event_formMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel dimensiones;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
    
}
